---
subtitle: "EpiEstim Results"
title: 'Supplementary Material A6'
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r Parameters and data}
library(EpiEstim)
library(ggplot2)
library(ggpubr)
library(Metrics)

parms=c(0.9,0.9,1/3,0.75)
u=parms[1]
uv=parms[2]
g=parms[3]
uA=parms[4]


#---Data---#

SimuNoisy013=read.csv('SimuNoisy0_013.csv')
SimuNoisy005=read.csv('SimuNoisy0_005.csv')

Simu=read.csv('Simu0_013.csv')
Srep=numeric(151)#generating incidence data from the not noisy simulated data
for (i in 1:151){ 
  Srep[i+1]=u*g*Simu$I[i]+uA*g*Simu$A[i]+uv*g*Simu$Iv[i]
}
SimuNotNoisy013=as.data.frame(Srep)
names(SimuNotNoisy013)=c('x')

Simu=read.csv('Simu0_005.csv')
Srep=numeric(151)#generating incidence data from the not noisy simulated data
for (i in 1:151){ 
  Srep[i+1]=u*g*Simu$I[i]+uA*g*Simu$A[i]+uv*g*Simu$Iv[i]
}
SimuNotNoisy005=as.data.frame(Srep)
names(SimuNotNoisy005)=c('x')



#--- Functions using Parametric Serial Interval ---#
Rt_daily=function(data, SI){
  t_start=seq(2, length(data$x)-1)
  t_end=t_start+1
  Rt=estimate_R(incid=data$x*888000,
            method='parametric_si',
            config = make_config(list(
              mean_si = SI['mu'], 
              std_si = SI['sd'], 
              t_start=t_start, 
              t_end =t_end)))
}

Rt_weekly=function(data, SI){
  Rt=estimate_R(incid=data$x*888000,
                method='parametric_si',
                config = make_config(list(
                  mean_si = SI['mu'], 
                  std_si = SI['sd'])))
}
```

```{r}
plot_R=function(Rt,v, step, noise){
' Plots the rulting Rt values on the same figure as the true
values and the ones obtained by DE'
  if (v==0.013){
    original=read.csv('Rt_013.csv')$x
    DE=read.csv('DERt013.csv')$Rt
  }
  if (v==0.005){
    original=read.csv('Rt_005.csv')$x
    DE=read.csv('DERt005.csv')$Rt
  }
  if (step=='Weekly'){
    original=original[7:151]
    #DE=numeric(145)
    DE=DE[7:151]
  }
  if (step=='Daily'){
    original=original[2:151]
    DE=DE[2:151]
  }
  
  Rt=as.data.frame(Rt[['R']])
  names(Rt)=c('t_start','t_end','Mean','Std','Q0.025',
              'Q0.05','Q0.25','Median','Q0.75','W0.95','Q0.975')
  Rt=cbind(Rt,original, DE)
  l=dim(Rt)[1]
  
  Rt=Rt[is.na(Rt$Mean)==FALSE,]
  
  Bias=mean(abs(Rt$Mean-Rt$original))#mean absolute bias between estimated and true Rt
  RMSE=rmse(Rt$original,Rt$Mean) #RMSE between estimated and true Rt
    
  gg=ggplot(Rt, aes(x=t_start))+
    labs(color='R')+
    geom_line(aes(y=Mean,col='Estimated Mean (EpiEstim)'))+
    geom_ribbon(aes(ymin=Q0.025, ymax=Q0.975),
                alpha=0.3)+
    geom_line(aes(y=original, col='Simulated'))+
    geom_line(aes(y=DE, col='DE estimates'))+
    xlab('Days')+
    ylab('Time-Varying R')+
    ggtitle(paste(step,'estimations / v=',v, '/',noise,'noise'))+
    scale_color_manual(values=c("#009E73","Blue","Black"))+
    theme(legend.key.size = unit(5, 'mm'), 
          plot.title = element_text(size = unit(7,'cm')),
          axis.text = element_text(size = unit(7,'cm')),
          axis.title = element_text(size = unit(9,'cm')),
          legend.text = element_text(size = unit(9, 'mm')),
          legend.title =element_text(size = unit(9, 'mm')),
          legend.position = 'bottom')
  plot(gg)
  print(Bias)
  print(RMSE)
  return(list(Bias,RMSE, gg))
}
```


```{r message=FALSE, warning=FALSE}
SI_Nishiura=c(mu=4.8, sd=2.3) #Nishiura et al. (2020) 
SI_Du=c(mu=3.96, sd=4.75) #Du et al. (2020)
SI_Sim=c(mu=5.8,sd=3) #mean incubation interval used in the simulation
#mu=mean latent period + mean pre-syptomatic period 



#---Commands---#
##-Daily and Weekly estimations using SI estimation from Nishiura et.al 2020-##
Rt013_N=Rt_weekly(SimuNoisy013, SI_Nishiura)
Rt005_N=Rt_weekly(SimuNoisy005, SI_Nishiura)
Rt013D_N=Rt_daily(SimuNoisy013, SI_Nishiura)
Rt005D_N=Rt_daily(SimuNoisy005, SI_Nishiura)
Rt_notnoisy0.013_N=Rt_weekly(SimuNotNoisy013, SI_Nishiura)
Rt_notnoisy0.013D_N=Rt_daily(SimuNotNoisy005, SI_Nishiura)

A=plot_R(Rt013_N, v=0.013,'Weekly',noise='Poisson')
B=plot_R(Rt005_N,v=0.005,'Weekly',noise='Poisson')
C=plot_R(Rt013D_N,v=0.013,'Daily',noise='Poisson')
D=plot_R(Rt005D_N,v=0.005,'Daily',noise='Poisson')
E=plot_R(Rt_notnoisy0.013_N, v=0.013,'Weekly',noise='No')
H=plot_R(Rt_notnoisy0.013D_N, v=0.013,'Daily',noise='No')
ggarrange(C[[3]],A[[3]],D[[3]],B[[3]],H[[3]],E[[3]],
          labels = c("a", "b","c","d","e","f"), 
          common.legend = TRUE, legend = "bottom", nrow=3, ncol=2)
ggsave(file = "EpiEstim_Nishiura.pdf", width = 7.30,height=7.55, units=c('in'))



##--- Daily and Weekly estimations using SI estimation from Du et.al 2020 ---##
Rt013_D=Rt_weekly(SimuNoisy013, SI_Du)
Rt005_D=Rt_weekly(SimuNoisy005, SI_Du)

Rt013D_D=Rt_daily(SimuNoisy013, SI_Du)
Rt005D_D=Rt_daily(SimuNoisy005, SI_Du)

Rt_notnoisy0.013_D=Rt_weekly(SimuNotNoisy013, SI_Du)
Rt_notnoisy0.013D_D=Rt_daily(SimuNotNoisy005, SI_Du)

A=plot_R(Rt013_D,v=0.013,'Weekly',noise='Poisson')
B=plot_R(Rt005_D,v=0.005,'Weekly',noise='Poisson')
C=plot_R(Rt013D_D,v=0.013,'Daily',noise='Poisson')
D=plot_R(Rt005D_D,v=0.005,'Daily',noise='Poisson')
E=plot_R(Rt_notnoisy0.013_D, v=0.013,'Weekly',noise='No')
H=plot_R(Rt_notnoisy0.013D_D, v=0.013,'Daily',noise='No')
ggarrange(C[[3]],A[[3]],D[[3]],B[[3]],H[[3]],E[[3]], 
          labels = c("a", "b","c","d","e","f"), 
          common.legend = TRUE, legend = "bottom",
          nrow=3,ncol=2)
ggsave(file = "EpiEstim_Du.pdf", width = 7.30,height=7.55, units=c('in'))
```

```{r}
##-Daily and Weekly estimations using SI estimation from the parameter values
#used for the simulation-##
Rt013_S=Rt_weekly(SimuNoisy013, SI_Sim)
Rt005_S=Rt_weekly(SimuNoisy005, SI_Sim)
Rt013D_S=Rt_daily(SimuNoisy013, SI_Sim)
Rt005D_S=Rt_daily(SimuNoisy005, SI_Sim)
Rt_notnoisy0.013_S=Rt_weekly(SimuNotNoisy013, SI_Sim)
Rt_notnoisy0.013D_S=Rt_daily(SimuNotNoisy005, SI_Sim)

A=plot_R(Rt013_S, v=0.013,'Weekly',noise='Poisson')
B=plot_R(Rt005_S,v=0.005,'Weekly',noise='Poisson')
C=plot_R(Rt013D_S,v=0.013,'Daily',noise='Poisson')
D=plot_R(Rt005D_S,v=0.005,'Daily',noise='Poisson')
E=plot_R(Rt_notnoisy0.013_S, v=0.013,'Weekly',noise='No')
H=plot_R(Rt_notnoisy0.013D_S, v=0.013,'Daily',noise='No')
ggarrange(C[[3]],A[[3]],D[[3]],B[[3]],H[[3]],E[[3]],
          labels = c("a", "b","c","d","e","f"), 
          common.legend = TRUE, legend = "bottom", nrow=3, ncol=2)
ggsave(file = "EpiEstim_Simu.pdf", width = 7.30,height=7.55, units=c('in'))

```

```{r}
# given mean SI: 4.8 (95% CrI: 3.8,6.1) Nishiura et al. (2020) given Weibull distribution
# and SD: 2.3 (95% CrI: 1.6, 3.5) 

#Normally distributed SI:
## mean: 3.96 (95% CI: 3.53, 4.39)
## SD: 4.75 (95% CI: 4.46, 5.07) Du et al. (2020)

#--- Functions using Uncertain Serial Interval ---#
Rt_Unc_daily=function(data){
  t_start=seq(2, length(data$x)-1)
  t_end=t_start+1
  Rt=estimate_R(incid=data$x*888000,
                method = "uncertain_si",
                config = make_config(list(
                mean_si = 4.8, std_mean_si = 1,
                min_mean_si = 3.8, max_mean_si = 5.8,
                std_si = 2.3, std_std_si = 0.5,
                min_std_si = 1.1, max_std_si = 3.5,
                n1 = 100, n2 = 100,
                t_start=t_start, 
                t_end =t_end)))
}

Rt_Unc_weekly=function(data){
  Rt=estimate_R(incid=data$x*888000,
                method = "uncertain_si",
                config = make_config(list(
                mean_si = 4.8, std_mean_si = 1,
                min_mean_si = 3.8, max_mean_si = 5.8,
                std_si = 2.3, std_std_si = 0.5,
                min_std_si = 1.1, max_std_si = 3.5,
                n1 = 100, n2 = 100)))
}
```


```{r}
RtU013=Rt_Unc_weekly(SimuNoisy013)
RtU005=Rt_Unc_weekly(SimuNoisy005)
RtU013_D=Rt_Unc_daily(SimuNoisy013)
RtU005_D=Rt_Unc_daily(SimuNoisy005)
RtU_notnoisy0.013=Rt_Unc_weekly(SimuNotNoisy013)
RtU_notnoisy0.013D=Rt_Unc_daily(SimuNotNoisy005)

A=plot_R(RtU013,v=0.013,'Weekly',noise='Poisson')
B=plot_R(RtU005,v=0.005,'Weekly',noise='Poisson')
C=plot_R(RtU013_D,v=0.013,'Daily',noise='Poisson')
D=plot_R(RtU005_D,v=0.005,'Daily',noise='Poisson')
E=plot_R(RtU_notnoisy0.013, v=0.013,'Weekly',noise='No')
H=plot_R(RtU_notnoisy0.013D, v=0.013,'Daily',noise='No')
ggarrange(C[[3]],A[[3]],D[[3]],B[[3]],H[[3]],E[[3]],
          labels = c("a","b","c","d","e","f"), 
          common.legend = TRUE, legend = "bottom", 
          nrow=3, ncol = 2)
ggsave(file = "EpiEstim_Uncertain.pdf", width = 7.30,height=7.55, units=c('in'))
```
